# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1 #100  # Hz

    mh5_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mh5_arm_controller:
  ros__parameters:
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity
gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    # command_interfaces:
    #   - position
    # state_interfaces:
    #   - position
      # - velocity