# MoveIt uses this configuration for controller management
# https://github.com/moveit/moveit2/blob/main/moveit_ros/planning/trajectory_execution_manager/cfg/TrajectoryExecutionDynamicReconfigure.cfg

trajectory_execution:
  execution_duration_monitoring: False
  allowed_execution_duration_scaling: 10.0
  allowed_goal_duration_margin: 30.0
  # execution_velocity_scaling: 0.1
  allowed_start_tolerance: 0.05
  wait_for_trajectory_completion: True

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - mh5_arm_controller
    - robotiq_gripper_controller

  mh5_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
    action_ns: follow_joint_trajectory
    default: true
    
  robotiq_gripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - robotiq_85_left_knuckle_joint