# MoveIt uses this configuration for controller management
# trajectory_execution:
#   allowed_execution_duration_scaling: 1.2
#   allowed_goal_duration_margin: 0.5
#   allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - mh5_arm_controller
    - robotiq_gripper_controller

  mh5_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
    action_ns: follow_joint_trajectory
    default: true
  robotiq_gripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - robotiq_85_left_knuckle_joint